name: main

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["*"]

permissions:
  contents: write

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: just build
      
      - run: just publish
